global:
  evaluation_interval: 15s
  scrape_timeout: 15s

scrape_configs:
  - job_name: "flink-pushgateway"
    scrape_interval: 5s
    honor_labels: true
    static_configs:
      - targets: ['pushgateway:9091']